### ISSUE TITLE
[Feature Request]  lights off when @ lock screen

### ISSUE THREAD

**Issue by gprime31** [LoLei/razer-cli#62]
Keyboard and mouse lights go off at lockscreen and/or when monitors go to sleep.
Thanks

**Comment by LoLei** [comment]
That seems more like a thing that the driver implementation ([openrazer](https://github.com/openrazer/openrazer)) should (maybe already does) support.

It can however also be done *using* razer-cli.  
Simply monitor your screen state in a script, and call `razer-cli -b 0` (lights off) and `razer-cli -b 100` (lights on) accordingly.

Here are some methods that could be used:
* https://unix.stackexchange.com/q/28181/164077
* https://askubuntu.com/q/858236/568802
* https://unix.stackexchange.com/q/246874/164077
* https://reddit.com/r/archlinux/comments/7p1i1h/how_to_monitor_when_display_went_to_sleep/

It's not something I'd include in razer-cli itself, since it is not supposed to run permanently as a service, unless you do that yourself in a way like those above, of course.

**Comment by LoLei** [comment]
I've actually found a setting in the openrazer config file that should do this out of the box.

```
devices_off_on_screensaver = True
```

For more information, see `man razer.conf`.
